#!/usr/bin/env ruby

require 'gtk3'

class Wetter

  def initialize(glade_path)
    @builder = Gtk::Builder.new
    @builder.add_from_file(glade_path)
    @builder.connect_signals { |handler| method (handler) }
    @main_window = @builder.get_object('WetterApplicationWindow')
  end

  def run
    @main_window.show
    Gtk.main
  end

  def quit
    Gtk.main_quit
  end

end

Wetter.new('wetter.ui').run